### ISSUE TITLE
Default selected option is empty

### ISSUE THREAD

**Issue by ghost** [shospodarets/angular-translate-yeoman#2]
Hi, 

can you please help me ? I can't get the default selected option to work its always empty, I use the same config as yours.

**Comment by shospodarets** [comment]
@roisafirorichard publish your solution and/or provide examples/description/links

**Comment by ghost** [comment]
Sure,I'm using yeoman with coffeescript, here is

app.coffee file 

'use strict'

angular
  .module 'sosAppApp', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngRoute',
    'ngSanitize',
    'ngTouch',
    'ui.bootstrap',
    'cfp.hotkeys',
    'ui.grid', 
    'ui.grid.edit',
    'ui.grid.cellNav',
    'ui.grid.selection',
    'ui.grid.pinning',
    'pascalprecht.translate',
    'tmh.dynamicLocale',
    'angularModalService',
    'ipCookie',
    'ui.date'
  ]
  .config ($routeProvider, $locationProvider, $translateProvider, tmhDynamicLocaleProvider, $httpProvider, LOCALES) ->
    $routeProvider
      .when '/home',
        templateUrl: 'views/main.html'
        controller: 'MainCtrl'
        controllerAs: 'main'
      .when '/login',
        templateUrl: 'views/login.html'
        controller: 'LoginCtrl'
        controllerAs: 'login'
      .otherwise
        redirectTo: '/login'

```
$translateProvider.useMissingTranslationHandlerLog()

$translateProvider.useStaticFilesLoader
  prefix: 'resources/locale-'
  suffix: '.json'
$translateProvider.preferredLanguage(LOCALES.preferredLocale)
$translateProvider.useLocalStorage()
tmhDynamicLocaleProvider.localeLocationPattern 'bower_components/angular-i18n/angular-locale_{{locale}}.js'
```

locales.coffee

angular.module 'sosAppApp'
  .constant 'LOCALES',
    'locales':
        'de_DE': 'Deutschland'
        'ch_CH': 'Schweiz'
        'at_AT': 'Österreich'
    'preferredLocale': 'de_DE'

and using the same directive for the select 
I'm I doing somthing wrong ?
Thanks for your help :)

**Comment by ghost** [comment]
I understand now why its not working
the problem comes from getLocaleDisplayName 
$translate.proposedLanguage() it returns undefined, how can I fix it please ?

**Comment by ghost** [comment]
Fixed I changed $translate.proposedLanguage() wih $translate.use()
Thanks again @malyw

**Comment by shospodarets** [comment]
Glad you fixed it )
