### ISSUE TITLE
how to translate text from controller

### ISSUE THREAD

**Issue by ShankzPatil** [shospodarets/angular-translate-yeoman#3]
how to translate text from controller?

scenario: i Have error/warning message in controller then how to translate appropriate.

**Comment by shospodarets** [comment]
Please describe the error in more details, provide the steps when it's happening and the logs.
Examples can be found here https://github.com/malyw/angular-translate-yeoman/blob/master/app/scripts/controllers/appCtrl.js#L23 , also it depdends on the dependency versions you use (please describe the Angular and depedencies versions).

**Comment by ShankzPatil** [comment]
thnx..
